### ISSUE TITLE
Install scala-cli?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/steward#22]
otel4s and scalac-options are broken due to https://github.com/scala-steward-org/scala-steward/issues/2948.  I wonder whether we could mitigate it by just installing scala-cli in the action?

**Comment by armanbilge** [comment]
Yeah I've been wondering the same. The follow-up question is, once it has scala-cli available, what will it do with it 😅

**Comment by fthomas** [comment]
It instructs Scala CLI to export the "project" to an sbt build and then extracts dependencies from that. If there are no genuine Scala CLI scripts, the exported sbt project will be empty and no additional dependencies are updated.

**Comment by rossabaker** [comment]
And if it runs amok, which it doesn't sound like it will, we should be able to close the PRs.

**Comment by armanbilge** [comment]
The steward action now installs it for us.
- https://github.com/scala-steward-org/scala-steward-action/releases/tag/v2.50.0
