### ISSUE TITLE
Auto rebase?

### ISSUE THREAD

**Issue by rossabaker** [typelevel/steward#6]
Are we missing a setting that will make the GitHub Action rebase and try again?  I'm looking at https://github.com/typelevel/otel4s/pull/17, for example.  The public instance used to do this, if I'm not mistaken.

**Comment by armanbilge** [comment]
This instance definitely does this. For example you can see in https://github.com/typelevel/discipline-specs2/pull/386. Not sure what's different here, we can dig into the laws.

**Comment by rossabaker** [comment]
Oh, I thought it retried failures periodically.  Alright, cool.
